### ISSUE TITLE
Hi from GoMule!

### ISSUE THREAD

**Issue by silospen** [pairofdocs/gomule-d2r#13]
Hey, just wanted to say hi and let you know that I've been working on D2R support over at Sourceforge https://sourceforge.net/p/gomule/git/ci/d2rSupport/tree/

**Comment by pairofdocs** [comment]
Hey @silospen,

Ohh! nice! 
I will look at your repo.

Most of the classes and functions that you have I've kept. There is this additional class that I added for a shared stash here
https://github.com/pairofdocs/gomule-d2r/pull/14  (WIP on making the shared stash)

**Comment by AcetateBarrel** [comment]
I downloaded the official gomule version from silopen to see what the differences are but it seems you guys use different file types for the atma stashes, cant load them.

**Comment by pairofdocs** [comment]
Yea there might be some difference there (but maybe just file extension, not structure of the stash itself)

@AcetateBarrel if you change the stash filename to `.d2x` will it work in gomule-official ?

The `.d2i` stashes created in this gomule-d2r are Atma structure
but the extension forAatma stashes is actually `.d2x` for LoD

**Comment by pairofdocs** [comment]
@silospen 
ohh I see 👍 

I have .d2i as `JM, numItems, Itemlist(no JM separators)`

![image](https://user-images.githubusercontent.com/76428136/136441028-dba2224b-70c3-47e9-b543-c4614b8d0a4a.png)

---


and .d2x format has `D2X, numItems, version, checksum, JM, Itemlist (with JM separators for LoD and no sep. for D2R)`

![image](https://user-images.githubusercontent.com/76428136/136441118-9ac0ab44-159d-4337-95c2-9aa3ab0bb0a5.png)

so my .d2i file can't be used like I thought, I'm missing the D2X characters, the version (97 like you said for D2R) and the checksum

**Comment by AcetateBarrel** [comment]
Just tried the converter for d2i>d2x and got this as error 

`Error

Stash Version Incorrect!
	at gomule.d2x.D2Stash.readAtmaItems(D2Stash.java:153)
	at gomule.d2x.D2Stash.<init>(D2Stash.java:78)
	at gomule.gui.D2FileManager.addItemList(D2FileManager.java:1597)
	at gomule.gui.D2ViewStash.connect(D2ViewStash.java:352)
	at gomule.gui.D2ViewStash.<init>(D2ViewStash.java:286)
	at gomule.gui.D2FileManager.openStash(D2FileManager.java:1508)
	at gomule.gui.D2FileManager.handleStash(D2FileManager.java:1484)
	at gomule.gui.D2FileManager.openStash(D2FileManager.java:1446)
	at gomule.gui.D2FileManager$26.actionPerformed(D2FileManager.java:901)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)`

**Comment by AcetateBarrel** [comment]
does anyone know what causing the error for me? Thanks
