### ISSUE TITLE
Not working as of 2.4

### ISSUE THREAD

**Issue by AronosAhri** [pairofdocs/gomule-d2r#23]
All characters and stashes open in a disconnected state as of 2.4.

**Comment by ajgringo619** [comment]
Same here (opened an issue a few hours ago). So far, my only "workaround" - and it only works in one direction - is to copy back one of my saved Shared stashes from before the patch, move items from my mule to it, then start D2R. The items can be accessed successfully with the 2.4 character, but items moved to the reopened stash can't be seen.

I really hope this is an easy fix; I've been working on my Grail and would loathe to have to make all the mules necessary to keep the items.

**Comment by AronosAhri** [comment]
Exact same boat, I noticed the same thing. Thankfully I have working saves from pre 2.4 that I can load up and bring in as sort of a one time use option, but it's a pain.

**Comment by Gubith** [comment]
>start  /b  java -jar GoMule.jar
java.lang.Exception: Incorrect Character version: 98

**Comment by immortal-jack** [comment]
I've actually seen this issue during PTR and I thought it was a PTR thing, I guess it's actually an 2.4 thing. This is the error message I'm getting when I try to open a character file in GoMule

`java.lang.Exception: Incorrect Character version: 98

        at gomule.d2s.D2Character.readChar(Unknown Source)
        at gomule.d2s.D2Character.<init>(Unknown Source)
        at gomule.gui.D2FileManager.addItemList(Unknown Source)
        at gomule.gui.D2ViewChar.connect(Unknown Source)
        at gomule.gui.D2ViewChar.<init>(Unknown Source)
        at gomule.gui.D2FileManager.openChar(Unknown Source)
        at gomule.gui.D2ViewProject$CharTreeNode.view(Unknown Source)
        at gomule.gui.D2ViewProject$3.mouseReleased(Unknown Source)
        at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
        at java.awt.Component.processMouseEvent(Unknown Source)
        at javax.swing.JComponent.processMouseEvent(Unknown Source)
        at java.awt.Component.processEvent(Unknown Source)
        at java.awt.Container.processEvent(Unknown Source)
        at java.awt.Component.dispatchEventImpl(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Window.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)`

**Comment by Gubith** [comment]
Devs looking at it, mentioned in here.
https://sourceforge.net/p/gomule/discussion/689770/thread/8f2f6fcc27/

**Comment by ajgringo619** [comment]
The new beta works, at least so far.

**Comment by AronosAhri** [comment]
With the beta, I can open my characters and stashes, but not sharedstashes.

Here's the error:

Error

Stash Version Incorrect!
	at gomule.d2x.D2Stash.readAtmaItems(D2Stash.java:153)
	at gomule.d2x.D2Stash.<init>(D2Stash.java:78)
	at gomule.gui.D2FileManager.addItemList(D2FileManager.java:1618)
	at gomule.gui.D2ViewStash.connect(D2ViewStash.java:352)
	at gomule.gui.D2ViewStash.<init>(D2ViewStash.java:286)
	at gomule.gui.D2FileManager.openStash(D2FileManager.java:1525)
	at gomule.gui.D2ViewProject$CharTreeNode.view(D2ViewProject.java:402)
	at gomule.gui.D2ViewProject$3.mouseReleased(D2ViewProject.java:126)
	at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by S1lverone** [comment]
hey just installed.
when opening chars, there is no items everything is empty. that goes for both d2r files and the old d2 files

**Comment by Impostor777** [comment]
Is it working? Having the same issue character disconnected
