### ISSUE TITLE
Can't get it to work

### ISSUE THREAD

**Issue by Slice0691** [pairofdocs/gomule-d2r#8]
I think I've followed all of the java instructions.  I get 4 pages of errors.  This is the first:

null
	at randall.d2files.D2FileReader.getCounterBoolean(Unknown Source)
	at randall.d2files.D2FileReader.getCounterInt(Unknown Source)
	at randall.d2files.D2TblFile.<init>(Unknown Source)
	at randall.d2files.D2TblFile.readAllFiles(Unknown Source)
	at gomule.gui.D2FileManager.<init>(Unknown Source)
	at gomule.gui.D2FileManager.<clinit>(Unknown Source)
	at gomule.GoMule$1.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

Thanks for your help.  I just installed this after your update of 2 hours ago.

**Comment by pairofdocs** [comment]
Do you see that when launching Gomule?
or is that when trying to load a save file?

what version of gomule did you use? Try the latest one here if you didn't use it already https://github.com/pairofdocs/gomule-d2r/archive/refs/heads/main.zip

And what's your java version?

that's seen in a cmd window when you type in `java -version`

**Comment by Slice0691** [comment]
This is when I try to run the GoMule.jar

java version "1.8.0_291" - just installed today

I just tried the download provided and got the same error.

I truly appreciate your help.

**Comment by Slice0691** [comment]
Solved.

I had a program called "Breezip" installed  that would try to run the .jar.  I was using the "open with" to start it with Java.

I deleted the Breezip app and GoMule opens as it should.

Thank you very much for your time.

**Comment by pairofdocs** [comment]
Ahh, good catch!

**Comment by wzurborg** [comment]
I am getting the same error when I start Java on the command line as follows, but when you close the error popup the program is starting anyway and is working correctly :
![grafik](https://user-images.githubusercontent.com/1320950/137443406-fdfa9f4d-bad2-4625-a785-5917187cde11.png)

I will investigate that myself later today.
